#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : accel-config
Version  : 4.1.8
Release  : 14
URL      : https://github.com/intel/idxd-config/archive/accel-config-v4.1.8/idxd-config-4.1.8.tar.gz
Source0  : https://github.com/intel/idxd-config/archive/accel-config-v4.1.8/idxd-config-4.1.8.tar.gz
Summary  : Configure accfg subsystem devices
Group    : Development/Tools
License  : CC0-1.0 GPL-2.0 LGPL-2.1 MIT
Requires: accel-config-bin = %{version}-%{release}
Requires: accel-config-lib = %{version}-%{release}
Requires: accel-config-license = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : buildreq-configure
BuildRequires : file
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(uuid)
BuildRequires : sed
BuildRequires : xmlto
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# accel-config
Utility library for controlling and configuring DSA (Intel® Data Streaming
Accelerator Architecture) and IAA (Intel® Analytics Accelerator Architecture)
sub-systems in the Linux kernel

%package bin
Summary: bin components for the accel-config package.
Group: Binaries
Requires: accel-config-license = %{version}-%{release}

%description bin
bin components for the accel-config package.


%package dev
Summary: dev components for the accel-config package.
Group: Development
Requires: accel-config-lib = %{version}-%{release}
Requires: accel-config-bin = %{version}-%{release}
Provides: accel-config-devel = %{version}-%{release}
Requires: accel-config = %{version}-%{release}

%description dev
dev components for the accel-config package.


%package lib
Summary: lib components for the accel-config package.
Group: Libraries
Requires: accel-config-license = %{version}-%{release}

%description lib
lib components for the accel-config package.


%package license
Summary: license components for the accel-config package.
Group: Default

%description license
license components for the accel-config package.


%prep
%setup -q -n idxd-config-accel-config-v4.1.8
cd %{_builddir}/idxd-config-accel-config-v4.1.8
pushd ..
cp -a idxd-config-accel-config-v4.1.8 buildavx2
popd
pushd ..
cp -a idxd-config-accel-config-v4.1.8 buildapx
popd

%build
## build_prepend content
bash autogen.sh
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1740075737
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --disable-docs
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
## build_prepend content
bash autogen.sh
## build_prepend end
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --disable-docs
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildapx/
## build_prepend content
bash autogen.sh
## build_prepend end
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -mapxf -mavx10.1-512 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -mapxf -mavx10.1-512 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -mapxf -mavx10.1-512 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --host=x86_64-clr-linux-gnu --disable-static --disable-docs
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :
cd ../buildapx;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1740075737
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/accel-config
cp %{_builddir}/idxd-config-accel-config-v%{version}/Documentation/COPYING %{buildroot}/usr/share/package-licenses/accel-config/cac5aabfbd6b7df58097e0f2efc0021152a31247 || :
cp %{_builddir}/idxd-config-accel-config-v%{version}/LICENSE_GPL_2_0 %{buildroot}/usr/share/package-licenses/accel-config/216629914867066060ebd55c489c17839d566b02 || :
cp %{_builddir}/idxd-config-accel-config-v%{version}/accfg/lib/LICENSE_LGPL_2_1 %{buildroot}/usr/share/package-licenses/accel-config/b6bf700828e326ac460dadc88c246f9ee43a29d4 || :
cp %{_builddir}/idxd-config-accel-config-v%{version}/ccan/array_size/LICENSE %{buildroot}/usr/share/package-licenses/accel-config/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/idxd-config-accel-config-v%{version}/ccan/build_assert/LICENSE %{buildroot}/usr/share/package-licenses/accel-config/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/idxd-config-accel-config-v%{version}/ccan/check_type/LICENSE %{buildroot}/usr/share/package-licenses/accel-config/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/idxd-config-accel-config-v%{version}/ccan/container_of/LICENSE %{buildroot}/usr/share/package-licenses/accel-config/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/idxd-config-accel-config-v%{version}/ccan/endian/LICENSE %{buildroot}/usr/share/package-licenses/accel-config/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/idxd-config-accel-config-v%{version}/ccan/list/LICENSE %{buildroot}/usr/share/package-licenses/accel-config/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/idxd-config-accel-config-v%{version}/ccan/minmax/LICENSE %{buildroot}/usr/share/package-licenses/accel-config/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/idxd-config-accel-config-v%{version}/ccan/short_types/LICENSE %{buildroot}/usr/share/package-licenses/accel-config/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/idxd-config-accel-config-v%{version}/ccan/str/LICENSE %{buildroot}/usr/share/package-licenses/accel-config/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v3
pushd ../buildapx/
%make_install_va
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/accel-config
/VA/usr/bin/accel-config
/usr/bin/accel-config

%files dev
%defattr(-,root,root,-)
/usr/include/accel-config/libaccel_config.h
/usr/lib64/libaccel-config.so
/usr/lib64/pkgconfig/libaccel-config.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libaccel-config.so.1.0.0
/VA/usr/lib64/libaccel-config.so.1.0.0
/usr/lib64/libaccel-config.so.1
/usr/lib64/libaccel-config.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/accel-config/216629914867066060ebd55c489c17839d566b02
/usr/share/package-licenses/accel-config/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305
/usr/share/package-licenses/accel-config/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3
/usr/share/package-licenses/accel-config/b6bf700828e326ac460dadc88c246f9ee43a29d4
/usr/share/package-licenses/accel-config/cac5aabfbd6b7df58097e0f2efc0021152a31247
